spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/consult_test?useUnicode = true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: sa12345
  thymeleaf:
    cache: false
    content-type: text/html
    mode: LEGACYHTML5
